export const cuisinesData = [
  { name: "African" ,selected: false},
  { name: "American" ,selected: false},
  { name: "British" ,selected: false},
  { name: "Cajun" ,selected: false},
  { name: "Caribbean" ,selected: false},
  { name: "Eastern European" ,selected: false},
  { name: "European" ,selected: false},
  { name: "French" ,selected: false},
  { name: "German" ,selected: false},
  { name: "Greek" ,selected: false},
  { name: "Indian" ,selected: false},
  { name: "Irish" ,selected: false},
  { name: "Italian" ,selected: false},
  { name: "Japanese" ,selected: false},
  { name: "Jewish" ,selected: false},
  { name: "Korean" ,selected: false},
  { name: "Latin American" ,selected: false},
  { name: "Mediterranean" ,selected: false},
  { name: "Mexican" ,selected: false},
  { name: "Middle Eastern" ,selected: false},
  { name: "Nordic" ,selected: false},
  { name: "Southern" ,selected: false},
  { name: "Spanish" ,selected: false},
  { name: "Thai" ,selected: false},
  { name: "Vietnamese" ,selected: false},
];
export const typeData = [
  { name: "Main Course" ,selected: false},
  { name: "Side Dish" ,selected: false},
  { name: "Dessert" ,selected: false},
  { name: "Appetizer" ,selected: false},
  { name: "Salad" ,selected: false},
  { name: "Bread" ,selected: false},
  { name: "Breakfast" ,selected: false},
  { name: "Soup" ,selected: false},
  { name: "Beverage" ,selected: false},
  { name: "Sauce" ,selected: false},
  { name: "Marinade" ,selected: false},
  { name: "Fingerfood" ,selected: false},
  { name: "Snack" ,selected: false},
  { name: "Drink" ,selected: false},
];
export const intolerancesData = [
  { name: "Dairy" ,selected: false},
  { name: "Egg" ,selected: false},
  { name: "Gluten" ,selected: false},
  { name: "Grain" ,selected: false},
  { name: "Peanut" ,selected: false},
  { name: "Seafood" ,selected: false},
  { name: "Sesame" ,selected: false},
  { name: "Shellfish" ,selected: false},
  { name: "Soy" ,selected: false},
  { name: "Sulfite" ,selected: false},
  { name: "Tree Nut" ,selected: false},
  { name: "Wheat" ,selected: false},

];
export const dietsData = [

        { name: "Gluten Free" ,selected: false},
        { name: "Ketogenic" ,selected: false},
        { name: "Vegetarian" ,selected: false},
        { name: "Lacto-Vegetarian" ,selected: false},
        { name: "Ovo-Vegetarian" ,selected: false},
        { name: "Vegan" ,selected: false},
        { name: "Pescetarian" ,selected: false},
        { name: "Paleo" ,selected: false},
        { name: "Primal" ,selected: false},
        { name: "Whole30" ,selected: false},
 
];
