export const cuisinesData = [
  { name: "African" },
  { name: "American" },
  { name: "British" },
  { name: "Cajun" },
  { name: "Caribbean" },
  { name: "Eastern European" },
  { name: "European" },
  { name: "French" },
  { name: "German" },
  { name: "Greek" },
  { name: "Indian" },
  { name: "Irish" },
  { name: "Italian" },
  { name: "Japanese" },
  { name: "Jewish" },
  { name: "Korean" },
  { name: "Latin American" },
  { name: "Mediterranean" },
  { name: "Mexican" },
  { name: "Middle Eastern" },
  { name: "Nordic" },
  { name: "Southern" },
  { name: "Spanish" },
  { name: "Thai" },
  { name: "Vietnamese" },
];
export const typeData = [
  { name: "Main Course" },
  { name: "Side Dish" },
  { name: "Dessert" },
  { name: "Appetizer" },
  { name: "Salad" },
  { name: "Bread" },
  { name: "Breakfast" },
  { name: "Soup" },
  { name: "Beverage" },
  { name: "Sauce" },
  { name: "Marinade" },
  { name: "Fingerfood" },
  { name: "Snack" },
  { name: "Drink" },
];
export const intolerancesData = [
  { name: "Dairy" },
  { name: "Egg" },
  { name: "Gluten" },
  { name: "Grain" },
  { name: "Peanut" },
  { name: "Seafood" },
  { name: "Sesame" },
  { name: "Shellfish" },
  { name: "Soy" },
  { name: "Sulfite" },
  { name: "Tree Nut" },
  { name: "Wheat" },

];
export const dietsData = [

        { name: "Gluten Free" },
        { name: "Ketogenic" },
        { name: "Vegetarian" },
        { name: "Lacto-Vegetarian" },
        { name: "Ovo-Vegetarian" },
        { name: "Vegan" },
        { name: "Pescetarian" },
        { name: "Paleo" },
        { name: "Primal" },
        { name: "Whole30" },
 
];
